name: Build Exe File

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:
    inputs:
      build_type:
        description: '选择构建类型'
        required: true
        default: 'windows-exe'
        type: choice
        options:
        - windows-exe

jobs:     
  build-windows-exe:
    name: Build Windows Executable
    runs-on: windows-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.build_type == 'windows-exe'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Build Windows executable
        run: |
          go mod tidy
          go mod download
          go build -o upload_tool.exe main.go

      - name: Upload to MinIO (via Go CLI)
        run: |
          ./tools/upload_tool.exe `
            --bucket "shopee" `
            --file "upload_tool.exe" `
            --object "upload_tool.exe"
        env:
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MINIO_SERVER_URL: ${{ secrets.MINIO_SERVER_URL }}
